"use client";

/**
 * Every problem the import found, grouped first and listed second.
 *
 * Four things about this endpoint decide the shape of this component:
 *
 *  1. **`meta.total` counts ROWS; `meta.stats.total_issues` counts ISSUE
 *     LINES.** One row can carry several problems, so the two numbers are
 *     routinely different and neither is "the number of errors". Both are shown
 *     with their unit written next to them, because a single unlabelled figure
 *     is wrong whichever one it is.
 *  2. **`meta.stats` is computed on page one only**, and later pages send
 *     `stats: null` with `stats_omitted: true`. So page one's summary is cached
 *     here for the life of the screen; re-reading it from page 2 would render
 *     an empty summary that looks like "no problems".
 *  3. **`per_page` is clamped to 100 by the server, silently.** Asking for more
 *     is not an error, it is fewer rows in a response shaped exactly like a
 *     complete one — the bug this repo has hit four times and now lints for.
 *     Every option offered here is at or below `MAX_PER_PAGE`.
 *  4. **The download is generated by the server.** The client holds one page;
 *     a CSV built from that is a short file that looks whole. `errors.csv` is
 *     streamed from the database per request instead.
 */

import { useCallback, useEffect, useRef, useState } from "react";
import { saveAs } from "file-saver";
import { AlertTriangle, Download, FileWarning, Inbox } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Spinner } from "@/components/ui/spinner";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { TablePagination } from "@/components/common";
import { getErrorMessage } from "@/lib/api-error";
import { notifyError } from "@/lib/notify";
import { todayISO } from "@/lib/format";
import { MAX_PER_PAGE } from "@/lib/paginate";
import { cn } from "@/lib/utils";
import { dataImportService } from "@/services/data-import.service";
import type {
  ImportErrorPageMeta,
  ImportRowIssue,
  ImportIssueSeverity,
} from "@/types/data-import";

/* ------------------------------------------------------------------ */
/* Contract widening                                                    */
/* ------------------------------------------------------------------ */

/**
 * An issue row as `ErrorReportBuilder::issuesFor()` actually emits it.
 *
 * `file` is the ORIGINAL FILENAME, not the kind — the kind travels separately
 * as `file_kind`. @/types/data-import types `file` as `ImportFileKind`, which
 * renders the same but reads as a promise this endpoint does not keep.
 */
type IssueRow = Omit<ImportRowIssue, "file"> & {
  file: string;
  file_kind?: string;
  record_number?: number;
};

/**
 * A grouped-summary entry as the API sends it.
 *
 * The builder emits `label` (the most common wording seen in the group) and
 * `distinct_messages`; the declared type names `sample_messages`, which no
 * response carries. Both are read, most-specific first, so this renders
 * whichever the server is actually sending.
 */
interface CategoryStat {
  category: string;
  count: number;
  severity?: ImportIssueSeverity;
  label?: string;
  distinct_messages?: number;
  sample_messages?: string[];
  distinct_messages_truncated?: boolean;
}

interface ErrorStats {
  total_issues: number;
  rows_reported?: number;
  by_severity: Partial<Record<ImportIssueSeverity, number>>;
  by_category: CategoryStat[];
  categories_truncated?: boolean;
}

type ErrorPageMeta = ImportErrorPageMeta & { stats?: ErrorStats | null };

/** The one line a category is worth, whichever key the server used for it. */
export function categoryExample(stat: CategoryStat): string | null {
  if (typeof stat.label === "string" && stat.label !== "") return stat.label;
  const sample = stat.sample_messages?.find((message) => message !== "");
  return sample ?? null;
}

/** "3 kinds of wording" — only when the server said how many. */
export function categoryWordingNote(stat: CategoryStat): string | null {
  const distinct = stat.distinct_messages ?? stat.sample_messages?.length;
  if (typeof distinct !== "number" || distinct <= 1) return null;
  return `${distinct}${stat.distinct_messages_truncated ? "+" : ""} different wordings`;
}

/** `import-errors-run-12-2026-08-30.csv`, dated in Manila time. */
export function errorReportFilename(runId: number | string): string {
  return `import-errors-run-${runId}-${todayISO()}.csv`;
}

/**
 * Page sizes. Every one at or below the server's own clamp — a literal above
 * 100 is an ESLint error in this repo, and for good reason: the server would
 * quietly serve 100 and the screen would have no way to know.
 */
const PER_PAGE_OPTIONS = [25, 50, MAX_PER_PAGE] as const;

const SEVERITY_STYLE: Record<ImportIssueSeverity, string> = {
  error: "bg-red-100 text-red-700 border-red-200 dark:bg-red-500/15 dark:text-red-400 dark:border-red-900",
  warning: "bg-amber-100 text-amber-700 border-amber-200 dark:bg-amber-500/15 dark:text-amber-400 dark:border-amber-900",
};

export interface ImportErrorsTableProps {
  runId: number | string;
  /** `error_report_available` from the status. False means nothing was staged. */
  reportAvailable?: boolean;
  /** `rows_with_errors` from the status, for the heading before page 1 lands. */
  rowsWithErrors?: number;
  className?: string;
}

export function ImportErrorsTable({
  runId,
  reportAvailable = true,
  rowsWithErrors,
  className,
}: ImportErrorsTableProps) {
  const [issues, setIssues] = useState<IssueRow[]>([]);
  const [meta, setMeta] = useState<ErrorPageMeta | null>(null);
  const [page, setPage] = useState(1);
  const [perPage, setPerPage] = useState<number>(PER_PAGE_OPTIONS[0]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [downloading, setDownloading] = useState(false);

  // Page one's summary, kept for the life of the screen. Page 2 onwards sends
  // `stats: null`, and re-reading it there would blank the block.
  const statsRef = useRef<ErrorStats | null>(null);
  const [stats, setStats] = useState<ErrorStats | null>(null);

  const load = useCallback(async () => {
    if (!reportAvailable) {
      setLoading(false);
      return;
    }
    setLoading(true);
    setError(null);

    try {
      const response = await dataImportService.errors(runId, { page, per_page: perPage });
      const nextMeta = (response?.meta ?? null) as ErrorPageMeta | null;

      setIssues((response?.data ?? []) as unknown as IssueRow[]);
      setMeta(nextMeta);

      // Only ever accept a stats block that was actually computed. `stats` is
      // null on later pages and `stats_omitted` says so outright.
      if (nextMeta?.stats && !nextMeta.stats_omitted) {
        statsRef.current = nextMeta.stats;
        setStats(nextMeta.stats);
      }
    } catch (err) {
      setError(getErrorMessage(err, "Could not load the list of problems."));
      setIssues([]);
    } finally {
      setLoading(false);
    }
  }, [runId, page, perPage, reportAvailable]);

  useEffect(() => {
    void load();
  }, [load]);

  const download = useCallback(async () => {
    setDownloading(true);
    try {
      const blob = await dataImportService.downloadErrorReport(runId);
      saveAs(blob, errorReportFilename(runId));
    } catch (err) {
      notifyError(err, "Could not download the report.");
    } finally {
      setDownloading(false);
    }
  }, [runId]);

  if (!reportAvailable) {
    return (
      <div className={cn("rounded-lg border border-dashed p-6 text-center", className)}>
        <Inbox className="mx-auto size-5 text-muted-foreground" aria-hidden="true" />
        <p className="mt-2 text-sm text-muted-foreground">
          No rows have been staged for this run yet, so there is nothing to report.
        </p>
      </div>
    );
  }

  const totalRows = meta?.total ?? rowsWithErrors ?? 0;
  const totalIssues = stats?.total_issues ?? null;
  const hasIssues = totalRows > 0 || issues.length > 0;

  return (
    <section className={cn("space-y-4", className)} aria-label="Rows to look at">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <h3 className="font-heading text-base font-medium">Rows to look at</h3>
          <p className="mt-0.5 text-sm text-muted-foreground tabular-nums">
            {totalRows.toLocaleString()} {totalRows === 1 ? "row" : "rows"} reported
            {totalIssues !== null ? (
              <>
                {" · "}
                {totalIssues.toLocaleString()}{" "}
                {totalIssues === 1 ? "issue line" : "issue lines"} in total
                <span className="text-muted-foreground/70"> (one row can carry several)</span>
              </>
            ) : null}
          </p>
        </div>

        <Button variant="outline" onClick={download} disabled={downloading || !hasIssues}>
          {downloading ? <Spinner /> : <Download />}
          Download full report
        </Button>
      </div>

      <p className="-mt-2 text-xs text-muted-foreground">
        Errors mean the row was not imported. Warnings mean it WAS imported with
        something adjusted — a contact number that was not a Philippine format is
        cleared and the member still lands — so a warning here is not a failure
        and is not counted as one in the tiles above.
      </p>

      {/* The grouped view: what an admin actually acts on. */}
      {stats && stats.by_category.length > 0 ? (
        <div className="rounded-lg border">
          <div className="flex flex-wrap items-center gap-2 border-b px-3 py-2">
            <span className="text-sm font-medium">Grouped by reason</span>
            {(["error", "warning"] as const).map((severity) => {
              const count = stats.by_severity?.[severity];
              if (typeof count !== "number" || count === 0) return null;
              return (
                <Badge key={severity} variant="outline" className={SEVERITY_STYLE[severity]}>
                  {count.toLocaleString()} {severity === "error" ? "errors" : "warnings"}
                </Badge>
              );
            })}
          </div>
          <ul className="divide-y">
            {stats.by_category.map((stat) => {
              const example = categoryExample(stat);
              const wording = categoryWordingNote(stat);
              return (
                <li key={`${stat.severity ?? ""}:${stat.category}`} className="px-3 py-2">
                  <div className="flex items-baseline justify-between gap-3">
                    <span className="text-sm font-medium">
                      {stat.severity ? (
                        <Badge
                          variant="outline"
                          className={cn("mr-2 align-middle", SEVERITY_STYLE[stat.severity])}
                        >
                          {stat.severity}
                        </Badge>
                      ) : null}
                      {stat.category}
                    </span>
                    <span className="shrink-0 text-sm tabular-nums text-muted-foreground">
                      {stat.count.toLocaleString()}{" "}
                      {stat.count === 1 ? "issue line" : "issue lines"}
                    </span>
                  </div>
                  {example ? (
                    <p className="mt-0.5 text-xs text-muted-foreground">
                      {example}
                      {wording ? <span className="text-muted-foreground/70"> · {wording}</span> : null}
                    </p>
                  ) : null}
                </li>
              );
            })}
          </ul>
          {stats.categories_truncated ? (
            <p className="border-t px-3 py-2 text-xs text-muted-foreground">
              Only the largest groups are listed. The downloaded report carries every one.
            </p>
          ) : null}
        </div>
      ) : null}

      {error ? (
        <div
          role="alert"
          className="flex items-start gap-3 rounded-lg border border-red-500/40 bg-red-500/10 p-4 text-sm"
        >
          <AlertTriangle className="mt-0.5 size-4 shrink-0 text-red-600" aria-hidden="true" />
          <div>
            <p className="font-medium text-red-900 dark:text-red-200">{error}</p>
            <Button variant="outline" size="sm" className="mt-2" onClick={() => void load()}>
              Try again
            </Button>
          </div>
        </div>
      ) : null}

      {loading && issues.length === 0 ? (
        <div className="flex items-center gap-2 rounded-lg border p-6 text-sm text-muted-foreground">
          <Spinner />
          Loading the list of problems…
        </div>
      ) : null}

      {!loading && !error && issues.length === 0 ? (
        <div className="rounded-lg border border-dashed p-6 text-center">
          <FileWarning className="mx-auto size-5 text-muted-foreground" aria-hidden="true" />
          <p className="mt-2 text-sm text-muted-foreground">
            No rows were reported. Nothing needs fixing.
          </p>
        </div>
      ) : null}

      {issues.length > 0 ? (
        <div className="rounded-lg border">
          <div className="overflow-x-auto">
            <Table>
              <TableHeader>
                {/* Problem comes third, ahead of the identifying columns: on a
                    phone the table scrolls sideways, and the column an admin has
                    to read to act is the one that must be reachable first. */}
                <TableRow>
                  <TableHead className="w-20">Row</TableHead>
                  <TableHead className="w-24">Severity</TableHead>
                  <TableHead>Problem</TableHead>
                  <TableHead>File</TableHead>
                  <TableHead>Reference</TableHead>
                  <TableHead>Field</TableHead>
                  <TableHead>Value in the file</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {issues.map((issue, index) => (
                  <TableRow key={`${issue.file}:${issue.row_number}:${issue.field ?? ""}:${index}`}>
                    <TableCell className="tabular-nums">{issue.row_number}</TableCell>
                    <TableCell>
                      <Badge variant="outline" className={SEVERITY_STYLE[issue.severity]}>
                        {issue.severity}
                      </Badge>
                    </TableCell>
                    {/* `TableCell` is `whitespace-nowrap` by default, which pushes
                        the widest prose in the feature off the side of the
                        viewport and clips it. The message column is the one
                        thing this screen exists to show, so it wraps. */}
                    <TableCell className="min-w-64 max-w-md whitespace-normal">
                      <span className="text-xs text-muted-foreground">{issue.category}</span>
                      <br />
                      {issue.message}
                    </TableCell>
                    <TableCell className="max-w-40 truncate" title={issue.file}>
                      {issue.file}
                    </TableCell>
                    <TableCell className="text-muted-foreground">
                      {[issue.account_no, issue.loan_no].filter(Boolean).join(" · ") || "—"}
                    </TableCell>
                    <TableCell className="text-muted-foreground">
                      {issue.field || "—"}
                    </TableCell>
                    <TableCell className="max-w-48 whitespace-normal break-words font-mono text-xs">
                      {issue.original_value || "—"}
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>

          <div className="px-3 pb-3">
            <TablePagination
              page={meta?.current_page ?? page}
              perPage={meta?.per_page ?? perPage}
              total={totalRows}
              perPageOptions={PER_PAGE_OPTIONS}
              onPageChange={setPage}
              onPerPageChange={(next) => {
                setPerPage(next);
                setPage(1);
              }}
            />
            <p className="pt-1 text-xs text-muted-foreground">
              Counted in rows. A row with three problems is one row here and three
              lines in the downloaded report.
            </p>
          </div>
        </div>
      ) : null}
    </section>
  );
}
