import type { Role, RoleConfig } from "@/types";

/**
 * What each role is DOCUMENTED to have — the roles screen reads this to seed a
 * role's permission grid and to label it.
 *
 * It is not the gate. Every guard in the app (`RouteGuard`, `PermissionGate`,
 * `usePermission().can`) asks the auth store, which holds `user.permissions`
 * as the server sent them. So editing this map cannot grant anyone anything,
 * and a role whose server-side grants have drifted from this list will still
 * behave exactly as the server says.
 */
export const ROLES: Record<Role, RoleConfig> = {
  admin: {
    label: "Admin",
    description: "Full access to all modules",
    permissions: [
      "dashboard:view",
      "borrowers:view",
      "borrowers:create",
      "borrowers:update",
      "borrowers:delete",
      "loans:view",
      "loans:create",
      "loans:update",
      "loans:delete",
      "loans:approve",
      "loans:reject",
      "loans:release",
      "payments:view",
      "payments:create",
      "payments:update",
      "payments:void",
      "collections:view",
      "collections:mark_collected",
      "reports:view",
      "reports:export",
      "settings:view",
      "settings:update",
      "users:view",
      "users:create",
      "users:update",
      "users:delete",
      "audit_logs:view",
      "audit_logs:export",
      "share_capital:view",
      "share_capital:create",
      "share_capital:update",
      "collaterals:view",
      "collaterals:create",
      "collaterals:update",
      "collaterals:delete",
      "gcash:view",
      "gcash:transact",
      "gcash:settings",
      // CSV migration. Deliberately on `admin` only — no other role in this map
      // gets it, and `super_admin` (which the backend also grants) has no entry
      // here at all; see the note on the `Role` union in @/types/rbac.
      "imports:process",
    ],
  },
  loan_officer: {
    label: "Loan Officer",
    description: "Manage loans and borrowers",
    permissions: [
      "dashboard:view",
      "borrowers:view",
      "borrowers:create",
      "borrowers:update",
      "loans:view",
      "loans:create",
      "loans:update",
      "loans:approve",
      "loans:reject",
      "loans:release",
      "payments:view",
      "collections:view",
      "reports:view",
      "share_capital:view",
      "share_capital:create",
      "collaterals:view",
      "collaterals:create",
      "collaterals:update",
    ],
  },
  cashier: {
    label: "Cashier",
    description: "Record payments and view borrowers",
    permissions: [
      "dashboard:view",
      "borrowers:view",
      "loans:view",
      "payments:view",
      "payments:create",
      "payments:update",
      "payments:void",
      "collaterals:view",
      "gcash:view",
      "gcash:transact",
    ],
  },
  general_bookkeeper: {
    label: "General Bookkeeper",
    description: "Releases approved loans after chairwoman confirmation",
    permissions: [
      "dashboard:view",
      "borrowers:view",
      "loans:view",
      "loans:release",
      "payments:view",
      "reports:view",
      "share_capital:view",
      "collaterals:view",
    ],
  },
  collector: {
    label: "Collector",
    description: "View and manage collections",
    permissions: [
      "borrowers:view",
      "loans:view",
      "collections:view",
      "collections:mark_collected",
      "collaterals:view",
    ],
  },
  viewer: {
    label: "Viewer",
    description: "Read-only access to dashboard and reports",
    permissions: ["dashboard:view", "reports:view", "collaterals:view"],
  },
  loan_processor: {
    label: "Loan Processor",
    description: "Prepares and submits loan drafts for approval; handles revisions from approvers",
    permissions: [
      "dashboard:view",
      "borrowers:view",
      "borrowers:create",
      "borrowers:update",
      "loans:view",
      "loans:create",
      "loans:update",
      "reports:view",
      "share_capital:view",
      "collaterals:view",
      "collaterals:create",
      "collaterals:update",
    ],
  },
  manager: {
    label: "Manager",
    description: "Branch manager — first-level approver in the loan approval chain",
    permissions: [
      "dashboard:view",
      "borrowers:view",
      "loans:view",
      "loans:approve",
      "loans:reject",
      "payments:view",
      "reports:view",
      "share_capital:view",
      "audit_logs:view",
      "users:view",
      "collaterals:view",
    ],
  },
  bod1: {
    label: "BOD1",
    description: "Board of Directors member 1 — second-level approver",
    permissions: [
      "dashboard:view",
      "borrowers:view",
      "loans:view",
      "loans:approve",
      "loans:reject",
      "reports:view",
      "share_capital:view",
      "collaterals:view",
    ],
  },
  bod2: {
    label: "BOD2",
    description: "Board of Directors member 2 — third-level approver",
    permissions: [
      "dashboard:view",
      "borrowers:view",
      "loans:view",
      "loans:approve",
      "loans:reject",
      "reports:view",
      "share_capital:view",
      "collaterals:view",
    ],
  },
  bod3: {
    label: "BOD3",
    description: "Board of Directors member 3 — fourth-level approver",
    permissions: [
      "dashboard:view",
      "borrowers:view",
      "loans:view",
      "loans:approve",
      "loans:reject",
      "reports:view",
      "share_capital:view",
      "collaterals:view",
    ],
  },
  bod4: {
    label: "BOD4",
    description: "Board of Directors member 4 — fifth-level approver",
    permissions: [
      "dashboard:view",
      "borrowers:view",
      "loans:view",
      "loans:approve",
      "loans:reject",
      "reports:view",
      "share_capital:view",
      "collaterals:view",
    ],
  },
  bod5: {
    label: "BOD5",
    description: "Board of Directors member 5 — sixth-level approver",
    permissions: [
      "dashboard:view",
      "borrowers:view",
      "loans:view",
      "loans:approve",
      "loans:reject",
      "reports:view",
      "share_capital:view",
      "collaterals:view",
    ],
  },
  bod6: {
    label: "BOD6",
    description: "Board of Directors member 6 — seventh-level approver",
    permissions: [
      "dashboard:view",
      "borrowers:view",
      "loans:view",
      "loans:approve",
      "loans:reject",
      "reports:view",
      "share_capital:view",
      "collaterals:view",
    ],
  },
  bod7: {
    label: "BOD7",
    description: "Board of Directors member 7 — final approver in the chain",
    permissions: [
      "dashboard:view",
      "borrowers:view",
      "loans:view",
      "loans:approve",
      "loans:reject",
      "reports:view",
      "share_capital:view",
      "collaterals:view",
    ],
  },
};

export const ROLE_OPTIONS = Object.entries(ROLES).map(([value, config]) => ({
  value: value as Role,
  label: config.label,
  description: config.description,
}));
