import type { Role, RoleConfig } from "@/types";

export const ROLES: Record<Role, RoleConfig> = {
  admin: {
    label: "Admin",
    description: "Full access to all modules",
    permissions: [
      "dashboard:view",
      "borrowers:view",
      "borrowers:create",
      "borrowers:update",
      "borrowers:delete",
      "loans:view",
      "loans:create",
      "loans:update",
      "loans:delete",
      "loans:approve",
      "loans:reject",
      "loans:release",
      "payments:view",
      "payments:create",
      "payments:update",
      "payments:void",
      "collections:view",
      "collections:mark_collected",
      "reports:view",
      "reports:export",
      "settings:view",
      "settings:update",
      "users:view",
      "users:create",
      "users:update",
      "users:delete",
      "audit_logs:view",
      "audit_logs:export",
      "share_capital:view",
      "share_capital:create",
      "share_capital:update",
    ],
  },
  loan_officer: {
    label: "Loan Officer",
    description: "Manage loans and borrowers",
    permissions: [
      "dashboard:view",
      "borrowers:view",
      "borrowers:create",
      "borrowers:update",
      "loans:view",
      "loans:create",
      "loans:update",
      "loans:approve",
      "loans:reject",
      "loans:release",
      "payments:view",
      "collections:view",
      "reports:view",
      "share_capital:view",
      "share_capital:create",
    ],
  },
  cashier: {
    label: "Cashier",
    description: "Record payments and view borrowers",
    permissions: [
      "dashboard:view",
      "borrowers:view",
      "loans:view",
      "payments:view",
      "payments:create",
      "payments:update",
      "payments:void",
    ],
  },
  collector: {
    label: "Collector",
    description: "View and manage collections",
    permissions: [
      "borrowers:view",
      "loans:view",
      "collections:view",
      "collections:mark_collected",
    ],
  },
  viewer: {
    label: "Viewer",
    description: "Read-only access to dashboard and reports",
    permissions: ["dashboard:view", "reports:view"],
  },
};

export const ROLE_OPTIONS = Object.entries(ROLES).map(([value, config]) => ({
  value: value as Role,
  label: config.label,
  description: config.description,
}));
