import type { Role, RoleConfig } from "@/types";

export const ROLES: Record<Role, RoleConfig> = {
  admin: {
    label: "Admin",
    description: "Full access to all modules",
    permissions: [
      "dashboard:view",
      "borrowers:view",
      "borrowers:create",
      "borrowers:update",
      "borrowers:delete",
      "loans:view",
      "loans:create",
      "loans:update",
      "loans:delete",
      "loans:approve",
      "loans:reject",
      "loans:release",
      "payments:view",
      "payments:create",
      "payments:update",
      "payments:void",
      "collections:view",
      "collections:mark_collected",
      "reports:view",
      "reports:export",
      "settings:view",
      "settings:update",
      "users:view",
      "users:create",
      "users:update",
      "users:delete",
      "audit_logs:view",
      "audit_logs:export",
      "share_capital:view",
      "share_capital:create",
      "share_capital:update",
    ],
  },
  loan_officer: {
    label: "Loan Officer",
    description: "Manage loans and borrowers",
    permissions: [
      "dashboard:view",
      "borrowers:view",
      "borrowers:create",
      "borrowers:update",
      "loans:view",
      "loans:create",
      "loans:update",
      "loans:approve",
      "loans:reject",
      "loans:release",
      "payments:view",
      "collections:view",
      "reports:view",
      "share_capital:view",
      "share_capital:create",
    ],
  },
  cashier: {
    label: "Cashier",
    description: "Record payments and view borrowers",
    permissions: [
      "dashboard:view",
      "borrowers:view",
      "loans:view",
      "payments:view",
      "payments:create",
      "payments:update",
      "payments:void",
    ],
  },
  general_bookkeeper: {
    label: "General Bookkeeper",
    description: "Releases approved loans after chairwoman confirmation",
    permissions: [
      "dashboard:view",
      "borrowers:view",
      "loans:view",
      "loans:release",
      "payments:view",
      "reports:view",
      "share_capital:view",
    ],
  },
  collector: {
    label: "Collector",
    description: "View and manage collections",
    permissions: [
      "borrowers:view",
      "loans:view",
      "collections:view",
      "collections:mark_collected",
    ],
  },
  viewer: {
    label: "Viewer",
    description: "Read-only access to dashboard and reports",
    permissions: ["dashboard:view", "reports:view"],
  },
  loan_processor: {
    label: "Loan Processor",
    description: "Prepares and submits loan drafts for approval; handles revisions from approvers",
    permissions: [
      "dashboard:view",
      "borrowers:view",
      "borrowers:create",
      "borrowers:update",
      "loans:view",
      "loans:create",
      "loans:update",
      "reports:view",
      "share_capital:view",
    ],
  },
  manager: {
    label: "Manager",
    description: "Branch manager — first-level approver in the loan approval chain",
    permissions: [
      "dashboard:view",
      "borrowers:view",
      "loans:view",
      "loans:approve",
      "loans:reject",
      "payments:view",
      "reports:view",
      "share_capital:view",
      "audit_logs:view",
      "users:view",
    ],
  },
  bod1: {
    label: "BOD1",
    description: "Board of Directors member 1 — second-level approver",
    permissions: [
      "dashboard:view",
      "borrowers:view",
      "loans:view",
      "loans:approve",
      "loans:reject",
      "reports:view",
      "share_capital:view",
    ],
  },
  bod2: {
    label: "BOD2",
    description: "Board of Directors member 2 — third-level approver",
    permissions: [
      "dashboard:view",
      "borrowers:view",
      "loans:view",
      "loans:approve",
      "loans:reject",
      "reports:view",
      "share_capital:view",
    ],
  },
  bod3: {
    label: "BOD3",
    description: "Board of Directors member 3 — fourth-level approver",
    permissions: [
      "dashboard:view",
      "borrowers:view",
      "loans:view",
      "loans:approve",
      "loans:reject",
      "reports:view",
      "share_capital:view",
    ],
  },
  bod4: {
    label: "BOD4",
    description: "Board of Directors member 4 — fifth-level approver",
    permissions: [
      "dashboard:view",
      "borrowers:view",
      "loans:view",
      "loans:approve",
      "loans:reject",
      "reports:view",
      "share_capital:view",
    ],
  },
  bod5: {
    label: "BOD5",
    description: "Board of Directors member 5 — sixth-level approver",
    permissions: [
      "dashboard:view",
      "borrowers:view",
      "loans:view",
      "loans:approve",
      "loans:reject",
      "reports:view",
      "share_capital:view",
    ],
  },
  bod6: {
    label: "BOD6",
    description: "Board of Directors member 6 — seventh-level approver",
    permissions: [
      "dashboard:view",
      "borrowers:view",
      "loans:view",
      "loans:approve",
      "loans:reject",
      "reports:view",
      "share_capital:view",
    ],
  },
  bod7: {
    label: "BOD7",
    description: "Board of Directors member 7 — final approver in the chain",
    permissions: [
      "dashboard:view",
      "borrowers:view",
      "loans:view",
      "loans:approve",
      "loans:reject",
      "reports:view",
      "share_capital:view",
    ],
  },
};

export const ROLE_OPTIONS = Object.entries(ROLES).map(([value, config]) => ({
  value: value as Role,
  label: config.label,
  description: config.description,
}));
