export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    LOGOUT: "/auth/logout",
    REFRESH: "/auth/refresh",
    ME: "/auth/me",
    FORGOT_PASSWORD: "/auth/forgot-password",
    RESET_PASSWORD: "/auth/reset-password",
    VERIFY_EMAIL: "/auth/verify-email",
  },
  DASHBOARD: {
    OVERVIEW: "/dashboard/overview",
    PORTFOLIO_SUMMARY: "/dashboard/portfolio-summary",
    COLLECTION_RATE: "/dashboard/collection-rate",
    CHARTS: "/dashboard/charts",
  },
  BORROWERS: {
    LIST: "/borrowers",
    DETAIL: (id: number) => `/borrowers/${id}`,
    CREATE: "/borrowers",
    UPDATE: (id: number) => `/borrowers/${id}`,
    DELETE: (id: number) => `/borrowers/${id}`,
    LOANS: (id: number) => `/borrowers/${id}/loans`,
    PAYMENTS: (id: number) => `/borrowers/${id}/payments`,
    LEDGER: (id: number) => `/borrowers/${id}/ledger`,
    DEACTIVATE: (id: number) => `/borrowers/${id}/deactivate`,
    REACTIVATE: (id: number) => `/borrowers/${id}/reactivate`,
    UPLOAD_PHOTO: (id: number) => `/borrowers/${id}/photo`,
    DELETE_PHOTO: (id: number) => `/borrowers/${id}/photo`,
  },
  CO_MAKERS: {
    LIST: (borrowerId: number) => `/borrowers/${borrowerId}/co-makers`,
    CREATE: (borrowerId: number) => `/borrowers/${borrowerId}/co-makers`,
    DETAIL: (id: number) => `/co-makers/${id}`,
    UPDATE: (id: number) => `/co-makers/${id}`,
    DELETE: (id: number) => `/co-makers/${id}`,
  },
  DOCUMENTS: {
    BORROWER_LIST: (borrowerId: number) => `/borrowers/${borrowerId}/documents`,
    BORROWER_UPLOAD: (borrowerId: number) => `/borrowers/${borrowerId}/documents`,
    CO_MAKER_LIST: (coMakerId: number) => `/co-makers/${coMakerId}/documents`,
    CO_MAKER_UPLOAD: (coMakerId: number) => `/co-makers/${coMakerId}/documents`,
    DETAIL: (id: number) => `/documents/${id}`,
    DELETE: (id: number) => `/documents/${id}`,
  },
  LOANS: {
    LIST: "/loans",
    DETAIL: (id: number) => `/loans/${id}`,
    CREATE: "/loans",
    UPDATE: (id: number) => `/loans/${id}`,
    DELETE: (id: number) => `/loans/${id}`,
    APPROVE: (id: number) => `/loans/${id}/approve`,
    REJECT: (id: number) => `/loans/${id}/reject`,
    RELEASE: (id: number) => `/loans/${id}/release`,
    SCHEDULE: (id: number) => `/loans/${id}/schedule`,
    RESTRUCTURE: (id: number) => `/loans/${id}/restructure`,
    AMORTIZATION_PREVIEW: (id: number) => `/loans/${id}/amortization-preview`,
    SUBMIT: (id: number) => `/loans/${id}/submit`,
    VOID: (id: number) => `/loans/${id}/void`,
  },
  LOAN_PRODUCTS: {
    LIST: "/loan-products",
    CREATE: "/loan-products",
    DETAIL: (id: number) => `/loan-products/${id}`,
    UPDATE: (id: number) => `/loan-products/${id}`,
    DELETE: (id: number) => `/loan-products/${id}`,
  },
  PAYMENTS: {
    LIST: "/payments",
    DETAIL: (id: number) => `/payments/${id}`,
    CREATE: "/payments",
    UPDATE: (id: number) => `/payments/${id}`,
    VOID: (id: number) => `/payments/${id}/void`,
  },
  COLLECTIONS: {
    LIST: "/collections",
    OVERDUE: "/collections/overdue",
    DUE_TODAY: "/collections/due-today",
    UPCOMING: "/collections/upcoming",
    MARK_COLLECTED: (id: number) => `/collections/${id}/collected`,
  },
  REPORTS: {
    GENERATE: "/reports/generate",
    LIST: "/reports",
    DAILY_COLLECTION: "/reports/daily-collection",
    PORTFOLIO: "/reports/portfolio",
    INCOME: "/reports/income",
  },
  USERS: {
    LIST: "/users",
    DETAIL: (id: number) => `/users/${id}`,
    CREATE: "/users",
    UPDATE: (id: number) => `/users/${id}`,
    DELETE: (id: number) => `/users/${id}`,
    UPDATE_ROLE: (id: number) => `/users/${id}/role`,
    TOGGLE_STATUS: (id: number) => `/users/${id}/status`,
    DEACTIVATE: (id: number) => `/users/${id}/deactivate`,
    REACTIVATE: (id: number) => `/users/${id}/reactivate`,
    RESET_PASSWORD: (id: number) => `/users/${id}/reset-password`,
  },
  AUDIT_LOGS: {
    LIST: "/audit-logs",
    DETAIL: (id: number) => `/audit-logs/${id}`,
    EXPORT: "/audit-logs/export",
  },
  ROLES: {
    LIST: "/roles",
    DETAIL: (id: number) => `/roles/${id}`,
  },
  BRANCHES: {
    LIST: "/branches",
    DETAIL: (id: number) => `/branches/${id}`,
    CREATE: "/branches",
    UPDATE: (id: number) => `/branches/${id}`,
  },
  SETTINGS: {
    PROFILE: "/settings/profile",
    BUSINESS: "/settings/business",
    LOAN_PRODUCTS: "/settings/loan-products",
    INTEREST_RATES: "/settings/interest-rates",
  },
  SYSTEM: {
    HEALTH: "/health",
  },
} as const;
