/**
 * API Endpoints — synced with Swagger spec at
 * https://api-lendyph.abedubas.dev/api/documentation
 *
 * Last synced: 2026-04-04
 */
export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/login",
    LOGOUT: "/auth/logout",
    REFRESH: "/auth/refresh",
    ME: "/auth/me",
    UPDATE_ME: "/auth/me",
    CHANGE_PASSWORD: "/auth/change-password",
  },
  BORROWERS: {
    LIST: "/borrowers",
    DETAIL: (id: number) => `/borrowers/${id}`,
    CREATE: "/borrowers",
    UPDATE: (id: number) => `/borrowers/${id}`,
    DELETE: (id: number) => `/borrowers/${id}`,
    BULK_DELETE: "/borrowers/bulk",
    BULK_DEACTIVATE: "/borrowers/bulk-deactivate",
    DEACTIVATE: (id: number) => `/borrowers/${id}/deactivate`,
    REACTIVATE: (id: number) => `/borrowers/${id}/reactivate`,
    UPLOAD_PHOTO: (id: number) => `/borrowers/${id}/photo`,
    DELETE_PHOTO: (id: number) => `/borrowers/${id}/photo`,
    UPLOAD_VALID_ID: (id: number) => `/borrowers/${id}/valid-ids`,
    LIST_VALID_IDS: (id: number) => `/borrowers/${id}/valid-ids`,
    LEDGER: (id: number) => `/borrowers/${id}/ledger`,
  },
  REGISTRATIONS: {
    LIST: "/borrowers",
    DETAIL: (id: number) => `/borrowers/${id}`,
    SUBMIT: "/borrowers",
    UPDATE: (id: number) => `/borrowers/${id}`,
    APPROVE: (id: number) => `/borrowers/${id}/reactivate`,
    REJECT: (id: number) => `/borrowers/${id}`,
  },
  CO_MAKERS: {
    LIST: (borrowerId: number) => `/borrowers/${borrowerId}/co-makers`,
    CREATE: (borrowerId: number) => `/borrowers/${borrowerId}/co-makers`,
    DETAIL: (id: number) => `/co-makers/${id}`,
    UPDATE: (id: number) => `/co-makers/${id}`,
    DELETE: (id: number) => `/co-makers/${id}`,
  },
  DOCUMENTS: {
    BORROWER_LIST: (borrowerId: number) => `/borrowers/${borrowerId}/documents`,
    BORROWER_UPLOAD: (borrowerId: number) => `/borrowers/${borrowerId}/documents`,
    CO_MAKER_LIST: (coMakerId: number) => `/co-makers/${coMakerId}/documents`,
    CO_MAKER_UPLOAD: (coMakerId: number) => `/co-makers/${coMakerId}/documents`,
    LOAN_LIST: (loanId: number) => `/loans/${loanId}/documents`,
    LOAN_UPLOAD: (loanId: number) => `/loans/${loanId}/documents`,
    DETAIL: (id: number) => `/documents/${id}`,
    DELETE: (id: number) => `/documents/${id}`,
  },
  LOANS: {
    LIST: "/loans",
    DETAIL: (id: number) => `/loans/${id}`,
    CREATE: "/loans",
    UPDATE: (id: number) => `/loans/${id}`,
    DELETE: (id: number) => `/loans/${id}`,
    APPROVE: (id: number) => `/loans/${id}/approve`,
    REJECT: (id: number) => `/loans/${id}/reject`,
    RELEASE: (id: number) => `/loans/${id}/release`,
    SUBMIT: (id: number) => `/loans/${id}/submit`,
    VOID: (id: number) => `/loans/${id}/void`,
    AMORTIZATION_PREVIEW: (id: number) => `/loans/${id}/amortization-preview`,
    AMORTIZATION_SCHEDULE: (id: number) => `/loans/${id}/amortization-schedule`,
    SUMMARY: (id: number) => `/loans/${id}/summary`,
    EXTEND: (id: number) => `/loans/${id}/extend`,
    TOGGLE_AUTO_PAY: (id: number) => `/loans/${id}/auto-pay`,
  },
  LOAN_DOCUMENTS: {
    DISCLOSURE: (loanId: number) => `/loans/${loanId}/disclosure`,
    PROMISSORY_NOTE: (loanId: number) => `/loans/${loanId}/promissory-note`,
  },
  LOAN_ADJUSTMENTS: {
    LIST: (loanId: number) => `/loans/${loanId}/adjustments`,
    CREATE: (loanId: number) => `/loans/${loanId}/adjustments`,
    DETAIL: (id: number) => `/loan-adjustments/${id}`,
    APPROVE: (id: number) => `/loan-adjustments/${id}/approve`,
    REJECT: (id: number) => `/loan-adjustments/${id}/reject`,
    APPLY: (id: number) => `/loan-adjustments/${id}/apply`,
  },
  REPAYMENTS: {
    LIST: (loanId: number) => `/loans/${loanId}/repayments`,
    LIST_ALL: "/repayments",
    CREATE: (loanId: number) => `/loans/${loanId}/repayments`,
    PREVIEW: (loanId: number) => `/loans/${loanId}/repayments/preview`,
    DETAIL: (id: number) => `/repayments/${id}`,
    VOID: (id: number) => `/repayments/${id}/void`,
  },
  LOAN_PRODUCTS: {
    LIST: "/loan-products",
    CREATE: "/loan-products",
    DETAIL: (id: number) => `/loan-products/${id}`,
    UPDATE: (id: number) => `/loan-products/${id}`,
    DELETE: (id: number) => `/loan-products/${id}`,
  },
  FEES: {
    LIST: "/fees",
    CREATE: "/fees",
    DETAIL: (id: number) => `/fees/${id}`,
    UPDATE: (id: number) => `/fees/${id}`,
    DELETE: (id: number) => `/fees/${id}`,
  },
  COLLATERAL_TYPES: {
    LIST: "/collateral-types",
    CREATE: "/collateral-types",
    DETAIL: (id: number) => `/collateral-types/${id}`,
    UPDATE: (id: number) => `/collateral-types/${id}`,
    DELETE: (id: number) => `/collateral-types/${id}`,
    REORDER: "/collateral-types/reorder",
  },
  COLLATERALS: {
    LIST: "/collaterals",
    CREATE: "/collaterals",
    DETAIL: (id: number) => `/collaterals/${id}`,
    UPDATE: (id: number) => `/collaterals/${id}`,
    DELETE: (id: number) => `/collaterals/${id}`,
    LIST_FOR_LOAN: (loanId: number) => `/loans/${loanId}/collaterals`,
    ATTACH: (loanId: number) => `/loans/${loanId}/collaterals`,
    DETACH: (loanId: number, collateralId: number) =>
      `/loans/${loanId}/collaterals/${collateralId}`,
  },
  REPORTS: {
    DUE_PAST_DUE: "/reports/due-past-due",
    LOAN_BALANCE_SUMMARY: "/reports/loan-balance-summary",
    RELEASES: "/reports/releases",
    REPAYMENTS: "/reports/repayments",
    STATEMENT_OF_ACCOUNT: (loanId: number) => `/reports/statement-of-account/${loanId}`,
    SUBSIDIARY_LEDGER: (borrowerId: number) => `/reports/subsidiary-ledger/${borrowerId}`,
    DAILY_COLLECTION: "/reports/daily-collection",
    INCOME: "/reports/income",
    AGING: "/reports/aging",
    BORROWERS: "/reports/borrowers",
    DISBURSEMENTS: "/reports/disbursements",
    EXPORT_RELEASES: "/reports/releases/export",
    EXPORT_REPAYMENTS: "/reports/repayments/export",
    EXPORT_DUE_PAST_DUE: "/reports/due-past-due/export",
  },
  DASHBOARD: {
    STATS: "/dashboard/stats",
    COLLECTIONS_TREND: "/dashboard/collections-trend",
    DAILY_DUES: "/dashboard/daily-dues",
    RECENT_TRANSACTIONS: "/dashboard/recent-transactions",
  },
  USERS: {
    LIST: "/users",
    DETAIL: (id: number) => `/users/${id}`,
    CREATE: "/users",
    UPDATE: (id: number) => `/users/${id}`,
    DEACTIVATE: (id: number) => `/users/${id}/deactivate`,
    REACTIVATE: (id: number) => `/users/${id}/reactivate`,
    RESET_PASSWORD: (id: number) => `/users/${id}/reset-password`,
  },
  AUDIT_LOGS: {
    LIST: "/audit-logs",
    DETAIL: (id: number) => `/audit-logs/${id}`,
    EXPORT: "/audit-logs/export",
  },
  ROLES: {
    LIST: "/roles",
    DETAIL: (id: number) => `/roles/${id}`,
    CREATE: "/roles",
    UPDATE: (id: number) => `/roles/${id}`,
    DELETE: (id: number) => `/roles/${id}`,
    DEACTIVATE: (id: number) => `/roles/${id}/deactivate`,
    REACTIVATE: (id: number) => `/roles/${id}/reactivate`,
  },
  BRANCHES: {
    LIST: "/branches",
    DETAIL: (id: number) => `/branches/${id}`,
    CREATE: "/branches",
    UPDATE: (id: number) => `/branches/${id}`,
  },
  SHARE_CAPITAL: {
    LEDGER_LIST: "/share-capital/ledger",
    LEDGER_CREATE: "/share-capital/ledger",
  },
  PLEDGES: {
    LIST: "/pledges",
    UPDATE: (id: number) => `/pledges/${id}`,
    TOGGLE_AUTO_CREDIT: (id: number) => `/pledges/${id}/auto-credit`,
    CREATE_ENTRY: (id: number) => `/pledges/${id}/entries`,
    BULK_ENTRIES: "/pledges/bulk-entries",
  },
  AUTO_CREDIT: {
    STATUS: "/auto-credit/status",
    PROCESS: "/auto-credit/process",
  },
  AUTO_PAY: {
    PREVIEW: "/auto-pay/preview",
    PROCESS: "/auto-pay/process",
  },
  SETTINGS: {
    APPROVAL_WORKFLOW: "/settings/approval-workflow",
  },
  SYSTEM: {
    HEALTH: "/health",
  },
} as const;
